from __future__ import annotations

import argparse
from dataclasses import dataclass
from itertools import product
from pathlib import Path
from typing import TypeAlias

import yaml

Scalar: TypeAlias = str | int | float | bool
FactTuple: TypeAlias = tuple[Scalar, ...]
PredicateFacts: TypeAlias = dict[str, list[FactTuple]]

OUTPUT_PATH = Path("src/datalog_conformance/_tests/generated/positive_nemo_1000.yaml")
SOURCE = "generated/positive-nemo-oracles-v1"
QUERY_CASES: tuple[tuple[str, str], ...] = (
    ("node_projection", "oracle-projection"),
    ("edge_projection", "oracle-projection"),
    ("two_step_join", "oracle-join"),
    ("recursive_path", "oracle-recursion"),
    ("root_reach", "oracle-recursion"),
    ("marked_path", "oracle-join"),
    ("same_color", "oracle-self-join"),
    ("color_lookup", "oracle-projection"),
    ("reverse_path", "oracle-recursion"),
    ("leaf_projection", "oracle-projection"),
    ("edge_then_path", "oracle-join"),
    ("mark_projection", "oracle-projection"),
    ("edge_color_join", "oracle-join"),
    ("path_union", "oracle-union"),
    ("marked_two_step", "oracle-join"),
    ("color_inverse", "oracle-projection"),
    ("root_descendant_path", "oracle-recursion"),
    ("marked_same_color", "oracle-self-join"),
    ("marked_source_edge", "oracle-join"),
    ("path_to_leaf", "oracle-recursion"),
)
QUERY_RULE_TEMPLATES: tuple[str, ...] = (
    "q_{g}_00(X) :- node_{g}(X).",
    "q_{g}_01(X, Y) :- edge_{g}(X, Y).",
    "q_{g}_02(X, Z) :- two_step_{g}(X, Z).",
    "q_{g}_03(X, Y) :- path_{g}(X, Y).",
    "q_{g}_04(Y) :- root_reach_{g}(Y).",
    "q_{g}_05(X, Y) :- marked_path_{g}(X, Y).",
    "q_{g}_06(X, Y) :- same_color_{g}(X, Y).",
    "q_{g}_07(X, C) :- color_{g}(X, C).",
    "q_{g}_08(X, Y) :- path_{g}(Y, X).",
    "q_{g}_09(X) :- leaf_{g}(X).",
    "q_{g}_10(X, Z) :- edge_{g}(X, Y), path_{g}(Y, Z).",
    "q_{g}_11(X) :- mark_{g}(X).",
    "q_{g}_12(X, Y, C) :- edge_{g}(X, Y), color_{g}(Y, C).",
    "q_{g}_13(X, Y) :- edge_{g}(X, Y).",
    "q_{g}_13(X, Y) :- path_{g}(X, Y).",
    "q_{g}_14(X, Z) :- edge_{g}(X, Y), edge_{g}(Y, Z), mark_{g}(Z).",
    "q_{g}_15(C, X) :- color_{g}(X, C).",
    "q_{g}_16(X, Y) :- root_{g}(R), path_{g}(R, X), path_{g}(X, Y).",
    "q_{g}_17(X, Y) :- mark_{g}(X), same_color_{g}(X, Y).",
    "q_{g}_18(X, Y) :- edge_{g}(X, Y), mark_{g}(X).",
    "q_{g}_19(X, Y) :- path_{g}(X, Y), leaf_{g}(Y).",
)


@dataclass(frozen=True, slots=True)
class Atom:
    predicate: str
    arguments: tuple[str, ...]


@dataclass(frozen=True, slots=True)
class Program:
    facts: PredicateFacts
    rules: list[str]


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate deterministic positive Datalog oracle cases verified by Nemo."
    )
    parser.add_argument("--output", type=Path, default=OUTPUT_PATH)
    parser.add_argument("--groups", type=int, default=50)
    args = parser.parse_args()

    if args.groups < 1:
        raise ValueError("--groups must be positive")

    cases = []
    for group_index in range(args.groups):
        group_id = f"g{group_index:03d}"
        program = _build_program(group_id, group_index)
        model = _evaluate_program(program)
        for query_index in range(20):
            predicate = f"q_{group_id}_{query_index:02d}"
            rows = sorted(model.get(predicate, set()), key=_row_sort_key)
            if not rows:
                raise RuntimeError(f"{predicate} unexpectedly produced no rows")
            cases.append(
                {
                    "name": f"generated_positive_{group_index:03d}_{query_index:02d}_{_case_slug(query_index)}",
                    "description": (
                        "Generated positive Datalog oracle case with visible facts, "
                        "visible rules, and expected rows verified against Nemo."
                    ),
                    "tags": [_query_tag(query_index), "oracle-tabular"],
                    "program": _yaml_program(program),
                    "expect": {predicate: [list(row) for row in rows]},
                }
            )

    document = {
        "source": SOURCE,
        "tags": ["core", "positive", "generated", "oracle", "nmo-direct"],
        "verification": {"implementation": "nmo", "kind": "direct"},
        "tests": cases,
    }

    args.output.parent.mkdir(parents=True, exist_ok=True)
    rendered = yaml.safe_dump(document, sort_keys=False, width=100)
    args.output.write_text(
        "# Generated by scripts/generate_positive_oracle_corpus.py; do not edit by hand.\n"
        + rendered,
        encoding="utf-8",
    )
    print(f"wrote {len(cases)} cases to {args.output.as_posix()}")
    return 0


def _build_program(group_id: str, group_index: int) -> Program:
    node_count = 5 + (group_index % 4)
    nodes = tuple(f"{group_id}_n{index}" for index in range(node_count))
    colors = ("red", "green", "blue")
    edge_rows = _edge_rows(nodes, group_index)
    mark_rows = [(node,) for index, node in enumerate(nodes) if (index + group_index) % 2 == 0]
    if not mark_rows:
        mark_rows = [(nodes[0],)]
    leaf_rows = [(nodes[-1],), (nodes[-2],)]
    color_rows = [(node, colors[(index + group_index) % len(colors)]) for index, node in enumerate(nodes)]

    facts: PredicateFacts = {
        f"seed_{group_id}": [(node,) for node in nodes],
        f"edge_{group_id}": edge_rows,
        f"mark_{group_id}": mark_rows,
        f"leaf_{group_id}": leaf_rows,
        f"color_{group_id}": color_rows,
        f"root_{group_id}": [(nodes[0],)],
    }
    rules = [
        f"node_{group_id}(X) :- seed_{group_id}(X).",
        f"path_{group_id}(X, Y) :- edge_{group_id}(X, Y).",
        f"path_{group_id}(X, Z) :- path_{group_id}(X, Y), edge_{group_id}(Y, Z).",
        f"two_step_{group_id}(X, Z) :- edge_{group_id}(X, Y), edge_{group_id}(Y, Z).",
        f"marked_path_{group_id}(X, Y) :- path_{group_id}(X, Y), mark_{group_id}(Y).",
        f"same_color_{group_id}(X, Y) :- color_{group_id}(X, C), color_{group_id}(Y, C).",
        f"root_reach_{group_id}(Y) :- root_{group_id}(X), path_{group_id}(X, Y).",
    ]
    for rule_template in QUERY_RULE_TEMPLATES:
        rules.append(rule_template.format(g=group_id))
    return Program(facts=facts, rules=rules)


def _edge_rows(nodes: tuple[str, ...], group_index: int) -> list[FactTuple]:
    rows = {(nodes[index], nodes[index + 1]) for index in range(len(nodes) - 1)}
    rows.add((nodes[0], nodes[-1]))
    if group_index % 2 == 0:
        rows.add((nodes[1], nodes[-1]))
    if group_index % 3 == 0:
        rows.add((nodes[0], nodes[2]))
    if group_index % 5 == 0:
        rows.add((nodes[-2], nodes[1]))
    if group_index % 7 == 0:
        rows.add((nodes[2], nodes[0]))
    return sorted(rows, key=_row_sort_key)


def _evaluate_program(program: Program) -> dict[str, set[FactTuple]]:
    facts = {predicate: set(rows) for predicate, rows in program.facts.items()}
    while True:
        next_facts = _apply_once(program.rules, facts)
        if next_facts == facts:
            return next_facts
        facts = next_facts


def _apply_once(
    rules: list[str],
    facts: dict[str, set[FactTuple]],
) -> dict[str, set[FactTuple]]:
    next_facts = {predicate: set(rows) for predicate, rows in facts.items()}
    domain = _active_domain(facts)
    for rule in rules:
        head, body = _parse_rule(rule)
        for substitution in _matching_substitutions(body, next_facts, domain):
            derived = _instantiate(head, substitution)
            next_facts.setdefault(derived.predicate, set()).add(derived.arguments)
    return next_facts


def _parse_rule(rule_text: str) -> tuple[Atom, list[Atom]]:
    text = rule_text.strip().removesuffix(".")
    if ":-" not in text:
        return _parse_atom(text), []
    head_text, body_text = text.split(":-", 1)
    return _parse_atom(head_text), [_parse_atom(item) for item in _split_atoms(body_text)]


def _parse_atom(atom_text: str) -> Atom:
    predicate, _, tail = atom_text.strip().partition("(")
    return Atom(
        predicate=predicate.strip(),
        arguments=tuple(item.strip() for item in tail.removesuffix(")").split(",")),
    )


def _split_atoms(body_text: str) -> list[str]:
    atoms: list[str] = []
    current: list[str] = []
    depth = 0
    for character in body_text:
        if character == "," and depth == 0:
            atom = "".join(current).strip()
            if atom:
                atoms.append(atom)
            current = []
            continue
        if character == "(":
            depth += 1
        elif character == ")" and depth > 0:
            depth -= 1
        current.append(character)
    atom = "".join(current).strip()
    if atom:
        atoms.append(atom)
    return atoms


def _matching_substitutions(
    body: list[Atom],
    facts: dict[str, set[FactTuple]],
    domain: tuple[str, ...],
) -> list[dict[str, str]]:
    if not body:
        return [{}]
    variables = sorted({arg for atom in body for arg in atom.arguments if _is_variable(arg)})
    if not variables:
        return [{}] if _body_holds(body, facts, {}) else []

    matches: list[dict[str, str]] = []
    for values in product(domain, repeat=len(variables)):
        substitution = dict(zip(variables, values, strict=True))
        if _body_holds(body, facts, substitution):
            matches.append(substitution)
    return matches


def _body_holds(
    body: list[Atom],
    facts: dict[str, set[FactTuple]],
    substitution: dict[str, str],
) -> bool:
    return all(
        _instantiate(atom, substitution).arguments in facts.get(atom.predicate, set())
        for atom in body
    )


def _instantiate(atom: Atom, substitution: dict[str, str]) -> Atom:
    return Atom(
        predicate=atom.predicate,
        arguments=tuple(substitution.get(argument, argument) for argument in atom.arguments),
    )


def _active_domain(facts: dict[str, set[FactTuple]]) -> tuple[str, ...]:
    values = {str(value) for rows in facts.values() for row in rows for value in row}
    return tuple(sorted(values)) or ("a",)


def _is_variable(value: str) -> bool:
    return value[:1].isupper()


def _yaml_program(program: Program) -> dict[str, object]:
    return {
        "facts": {
            predicate: [list(row) for row in rows]
            for predicate, rows in sorted(program.facts.items())
        },
        "rules": program.rules,
    }


def _case_slug(query_index: int) -> str:
    return QUERY_CASES[query_index][0]


def _query_tag(query_index: int) -> str:
    return QUERY_CASES[query_index][1]


def _row_sort_key(row: FactTuple) -> tuple[tuple[str, str], ...]:
    return tuple((type(value).__name__, repr(value)) for value in row)


if __name__ == "__main__":
    raise SystemExit(main())
